### PR TITLE
Feature/persistent docker container on windows

### PR DESCRIPTION
**Pull request by migerh**
Implements #269

### CODE REVIEW

**Comment by derwok** [comment]
From the point of reading, this looks very promising to me! Thanks!

A few thoughts you may comment on:

1. The average windows user (or even windows admin) maybe is more comfortable with nano than vim? Maybe we should use nano in the howto?
1. Whatever editor we use in the howto - we should add it to our 4minitz main image (I can do this in BUILD.sh inside .docker/, when we agree on one of the two editors). So the user has no need to install an editor first. Maybe the underlying machine has no connection to the net?
1. Logging into the storage container to change settings.json is rather cumbersome  -storing attachments there seems also a little bit complicated to me, looking up log file content also. Would it be possible to only put the MongoDB stuff inside the storage container? All other stuff did non had any problems when storing on the host file system. But I don't know if we can separate this?

Due to lack of Win10Pro machine I can not walk through the how to.
So, maybe we can ask Felix or Rob to check?

Thanks.
WOK

**Comment by migerh** [comment]
1. Sure. I just replaced vim with nano in the guide.
2. Sure, makes sense.
3. I understand that it makes sense to simplify editing the settings file and to make the logs more easily accessible, but why would an admin want to access the attachments on a file system level? He should do that only for backup and restore purposes. And backing up the attachments without the database makes no sense and mongodb can only be accessed by running a terminal or a backup script from inside the container. So I'd say the attachments and the database should stay close together. To separate the logging and settings from the database we need at least two separate volumes, one that should be used via a data storage container and one that is mounted from a host directory. [Apparently it is possible to mount multiple data volume containers](https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container-volumes-from) into the same container, but I haven't seen anything that says you can mix host directories and data volume containers. Maybe if you create the data storage container like this :thinking: 

```
docker create -v /4minitz_storage -v <local directory>:/4minitz_logs_and_settings --name 4minitz-storage 4minitz/4minitz
```

**Comment by derwok** [comment]
OK. I see, splitting will also bring "communication" problems to admin (backup etc.). So, let's leave all in one container.

But one question remains to me:
If I understand correctly: we use a second instance of the 4minitz image here for storage, right? What does this have for advantages compared to an "bare" OS iamge? Why to we use a second 4minitz/4minitz container for storage? Is there anything (except for OS & nano) in the image that is needed? We use neither node, mongo, 4minitz-binary in the storage container?
Are there disadvantages? When 4minitz updates the main image and user pulls new 4minitz/4minitz, will the storage image be still usable? Will it consume more RAM more host storage place?

OR to rephrase it: would it be possible to show steps to create an empty storage image (with only OS & nano editor)? 

The Mac/Lunix Howto works with an initial empty host-directory 4minitz_storage. IF there is no 4minitz_settings.json . then 4minitz.sh will copy this file once. Maybe this aproach may also work on the "Storage container" scenario on Windows - with a suggested empty image/container?

**Comment by migerh** [comment]
[See here](https://stackoverflow.com/questions/25845785/most-appropriate-container-for-a-data-only-container) for a few reasons why it is a good idea to use the same image. One of the reasons mentioned is that the data volume container doesn't run, so it does not consume any ressources other than disk space. But since they are based on the same image, this is exactly 0 byte, at least in the beginning.

**Comment by derwok** [comment]
Thx. Will merge in!

**Pull request merged**
