### PR TITLE
WIP: Internalization of 4Mintz

### PR DESCRIPTION
**Pull request by itrich**
This PR introduces a new feature to 4Mintiz: **Multilingual Support**. For this, I added the packages meteor:universe-i18n and meteor:universe-i18n-blaze. Most of the work will consist of finding all hard-coded strings and replace them with appropriate message format strings. As soon as all strings have been found, I will upload the language file en-us.yml to Crowdin for easier collaborative translation.

### CODE REVIEW

**Comment by derwok** [comment]
@itrich Hey!! In a busy work week, I just wanted to pop by and say a big "Thank you" for this initiative. Greatly appreciated that you work on issue #30. 
When the dust has settled and things work as expected we sure want to merge your work.

For the time being please ignore the red travis tests. We need to invest some time there...

Bye. WOK.

**Comment by itrich** [comment]
Strings that won't be translated with this PR:
- All console.log messages
- All Meteor.Error messages

However, if someone is keen on doing this task of diligence, simply grep for the above methods.

**Comment by derwok** [comment]
> Strings that won't be translated with this PR:
> 
>     * All console.log messages
>     * All Meteor.Error messages

Yes, I agree that we can keep these "admin only strings" in English.

**Comment by derwok** [comment]
Hi @itrich ,
I'm really looking forward to this feature... but no commits since >4 weeks - yet the pull request is still labeled "WIP". Is the PR ready for review & merge? Can we help somehow? Or should we just wait?

Keep up the good work!
WOK.

**Comment by itrich** [comment]
Hi @derwok,

unfortunately I had to focus on other projects. I'm opening my PR to maintainers and looking forward to further collaboration!

Best wishes,
Eduard

**Comment by derwok** [comment]
> unfortunately I had to focus on other projects. I'm opening my PR to maintainers and looking forward to further collaboration!

Happy new year, first!!! Hope all family fine!

@itrich Did you have the chance to open your repo's pull request branch for maintainers?
I just tried a test push - returned with error.
grafik

**Comment by itrich** [comment]
Strange, because I checked the option „Allow edits from maintainers.“
However, I gave you write access to my repository. You should now be able to commit to this feature branch.

**Comment by itrich** [comment]
Todo:
- [ ] Make the server side locale configurable, see: [server/main.server.js]. (https://github.com/buehl/4minitz/blob/8df368eb4a2538ea4df6109ab941b0b4489544f4/server/main.server.js#L34)

**Comment by derwok** [comment]
> Todo:
> 
>     * [ ]  Make the server side locale configurable, see: [server/main.server.js]. (https://github.com/buehl/4minitz/blob/8df368eb4a2538ea4df6109ab941b0b4489544f4/server/main.server.js#L34)

When is that locale used?
My understanding is: whenever a user triggers a server side request (e.g. Meteor-Method) that users session and that users locale is set in server scope. So this default server side locale is only needed when an action is triggered without logged in user. Then we are at "normal error reporting mode" - and that language is english, right?

**Comment by derwok** [comment]
@itrich Please see https://github.com/buehl/4minitz/commit/d9b0e23b3e4c91ad85fd7e8ff3e9a629c527bf19

The i18n tester script reports the following missing keys in English YAML:

```
npm run test:i18n

> 4Minitz@1.6.0-develop test:i18n _js/4minutes
> node tests/i18n/test_i18n_resources.js

Test_I18N_Resources
-------------------
Test if all needed string resources used in code are present in YAML: _js/4minutes/tests/i18n/../../both/i18n/en.i18n.yml
#keys in YAML: 294
#keys in .js: 90
I18N-ERROR: >buttons.OK< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/admin/adminRegisterUser.js

I18N-ERROR: >Minutes.history< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/minutesedit.js

#keys in .html: 409
I18N-ERROR: >buttons.OK< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/admin/adminRegisterUser.js

I18N-ERROR: >Minutes.history< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/minutesedit.js

I18N-ERROR: >Admin.Register.Label< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/admin/adminRegisterUser.html

I18N-ERROR: >Item.Filter.Usage.body< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/dialogs/filterUsage.html

I18N-ERROR: >Item.Filter.Usage.keyword< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/dialogs/filterUsage.html

I18N-ERROR: >Item.Filter.Usage.format< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/dialogs/filterUsage.html

I18N-ERROR: >Item.Filter.Usage.values< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/dialogs/filterUsage.html

I18N-ERROR: >Item.Filter.Usage.eg< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/dialogs/filterUsage.html

I18N-ERROR: >Dialog.ConfirmDeleteMinutes.really< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogDeleteMinutes.html

I18N-ERROR: >Dialog.ConfirmDeleteMinutes.newTopics< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogDeleteMinutes.html

I18N-ERROR: >Dialog.ConfirmDeleteMinutes.closedTopicsAdditionally< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogDeleteMinutes.html

I18N-ERROR: >Dialog.ConfirmDeleteMinutes.closedTopics< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogDeleteMinutes.html

I18N-ERROR: >Dialog.ConfirmFinalizeMinutes.really< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogFinalize.html

I18N-ERROR: >Dialog.ConfirmFinalizeMinutes.sendActionItems< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogFinalize.html

I18N-ERROR: >Dialog.ConfirmFinalizeMinutes.sendMinutes< not found in YAML needed by:
_js/4minutes/tests/i18n/../../client/templates/minutes/confirmationDialogFinalize.html
``` 
This was a "quick hack" just out of curiosity... 
I just checked a few - the reports were real errors.
Could you eventually solve the reported issues above?
If there are no false positives, we could eventually include this test step into TRAVIS builds...

**Comment by itrich** [comment]
> > Todo:
> > ```
> > * [ ]  Make the server side locale configurable, see: [server/main.server.js]. (https://github.com/buehl/4minitz/blob/8df368eb4a2538ea4df6109ab941b0b4489544f4/server/main.server.js#L34)
> > ```
> 
> When is that locale used?
> My understanding is: whenever a user triggers a server side request (e.g. Meteor-Method) that users session and that users locale is set in server scope. So this default server side locale is only needed when an action is triggered without logged in user. Then we are at "normal error reporting mode" - and that language is english, right?

This will be the case then 4Minitz! sends out the agenda to the participants via mail. What will be the language of the mail if the user set the language to automatic (decided by the browser)? I will have a look at this issue today. 😃

**Comment by derwok** [comment]
> > * [ ]  Make the server side locale configurable, see: [server/main.server.js]. 
>What will be the language of the mail if the user set the language to automatic (decided by the browser)? I will have a look at this issue today. 😃

Hmmm... let me think - maybe I'm wrong - The "auto" is a concept that the i18n package does not know. So, when some user triggers sending agenda, this user will always have a specific locale ('xx' code). This language code will be the session language that is then set on server side (temporarily) when user's client calls server code.

So I guess: it will "just work"(TM)...
as soon as we have translated the server-side-only strings (like EMail-Texts and so).

**Comment by derwok** [comment]
See here:
https://github.com/vazco/meteor-universe-i18n
```
i18n.setOptions({
     sameLocaleOnServerConnection: true
``` 
=> 'true' is the default and  according to API doc does: `synchronizes server connection with locale on client. (method invoked by client will be with client side locale)`

**Comment by itrich** [comment]
I‘m sorry, but I hadn’t the time to continue my work. All my changes have been pushed. You can merge the branches in order to continue the work.

**Comment by derwok** [comment]
> I‘m sorry, but I hadn’t the time to continue my work. All my changes have been pushed. You can merge the branches in order to continue the work.

OK. No problem - thanks for clarification - and of course thanks for all the huge amount of work you already put into this PR... Greatly appreciated. 

So, this evening I'll polish these last issues and then (hopefully) merge:
* [X] Check and fix the I18N errors reported by the I18N test script (see above)
* [ ] Fix (or tolerate) the 4 x TODOs found by Codeclimate

**Comment by migerh** [comment]
Merged via command line.

Thanks again for all that work!

**Pull request closed without merging**
